[version]
current = "5.0.1"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "chore: bumped version to {new_version}"
tag_template = "{new_version}"

[[file]]
src = "pyproject.toml"
search = 'version = "{current_version}"'

[[file]]
src = "src/aio_net_events/version.py"
version_template = "({major}, {minor}, {patch})"
search = "__version_info__ = {current_version}"

[[before_commit]]
name = "Run tests"
cmd = "poetry run pytest && pre-commit run --all-files"
